Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,28 +1,53 @@
 name: conchayoro-pipeline
+
 on:
-    push:
-        branches: [ main ]
+  push:
+    branches: [main]
+
 jobs:
-    build:
-        runs-on: ubuntu-latest
-        steps:
-        - uses: actions/checkout@v3
-        - uses: actions/upload-artifact@v3
-          with:
-                name: deploy
-                path: index.html
-    deploy:
-        runs-on: ubuntu-latest
-        needs: build
-        env:
-            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
-            AWS_EC2_METADATA_DISABLED: true
-            BUCKET_S3: ${{ vars.BUCKET_S3 }}
-        steps:
-          - uses: actions/download-artifact@v3
-            with:
-                name: deploy
-                path: index.html
-          - run: aws s3 cp index.html s3://$BUCKET_S3 --recursive --acl public-read
+  build:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: deploy
+          path: index.html
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+
+    strategy:
+      matrix:
+        environment: [homologacao, producao]
+
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
+      AWS_EC2_METADATA_DISABLED: true
+
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: deploy
+          path: index.html
+
+      - name: Deploy to S3
+        run: |
+          if [ "${{ matrix.environment }}" == "homologacao" ]; then
+            BUCKET_S3="${{ secrets.BUCKET_S3_HOMOLOGACAO }}"
+          elif [ "${{ matrix.environment }}" == "producao" ]; then
+            BUCKET_S3="${{ secrets.BUCKET_S3_PRODUCAO }}"
+          else
+            echo "Invalid environment specified"
+            exit 1
+          fi
+
+          aws s3 cp index.html s3://$BUCKET_S3 --recursive --acl public-read
